#!/bin/bash

xset r rate 300 50                                          # Speed xrate up
setxkbmap -option caps:swapescape                           # Swap capslock and esc key
xwallpaper --zoom $HOME/.config/wallpapers/08.jpg           # Set wallpaper
picom -b &                                                  # Transparency
pidof ibus-daemon > /dev/null || ibus-daemon -drx &         # Start ibus-daemon
nm-applet &                                                 # Netework manager applet
dwm-bar &                                                   # Start status bar
