#!/bin/bash

xset r rate 300 50 &                                        # Speed xrate up
xwallpaper --zoom $HOME/wallpapers/wallpaper5.jpg &      # Set wallpaper
picom -b &                                                  # Transparency
pidof ibus-daemon > /dev/null || ibus-daemon -drx &         # Start ibus-daemon
nm-applet &                                                 # Netework manager applet
$HOME/.config/dynamic-bar/bar.sh &                          # Run status bar
